export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

  
  export default function RootLayout({ children }) {
    return (
     <>
        {children}
        <h2 className="text-2xl mt-10">Other Products you may like</h2>
          
     </>
          
       
    )
  }