import "./globals.css";

export const metadata = {
  title: {
    default: "hey there",
    absolute: "",
    template: "%s | Learning Next js",
  },
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
   
      <body className="max-w-[1000px] mx-auto">
        <nav className=" bg-orange-600 h-20 max-w-[1000px] mx-auto mb-10">header</nav>
        {children}
        <footer className="bg-violet-500 h-20 max-w-[1000px] mx-auto mt-10">Footer</footer>
      </body>
    
    </html>
  )
}
